env: test

shared:
  consul:
    address: http://localhost:8500

  vault:
    address: http://localhost:8200
    token: 94e1a9ed-5d72-5677-27ab-ebc485cca368

  templates:
    database:
      path: templates/database.yml.erb
      dest: rendered/database.yml
      ttl: 10 # seconds

    elements:
      paths:
        - templates/elements/air.txt
        - templates/elements/fire.txt
      dest: rendered/elements.txt
      vars:
        air: 1
        fire: 2

    more_elements:
      path: templates/elements/air.txt
      paths:
        - templates/elements/fire.txt
        - templates/elements/water.txt
      dest: rendered/more_elements.txt
      vars:
        air: 1
        fire: 2
        water: 3

    consul_elements:
      consul_keys:
        - templates/elements/earth
        - templates/elements/love
      dest: rendered/consul_elements.txt
      vars:
        earth: 4
        love: 5

    more_consul_elements:
      consul_key: templates/elements/earth
      consul_keys:
        - templates/elements/love
        - templates/elements/aziz
      dest: rendered/more_consul_elements.txt
      vars:
        earth: 4
        love: 5
        aziz: 'Light!'

    multi_pass:
      path: templates/elements/air.txt
      consul_key: templates/elements/earth
      paths:
        - templates/elements/fire.txt
        - templates/elements/water.txt
      consul_keys:
        - templates/elements/love
        - templates/elements/aziz
      dest: rendered/multi_pass.txt
      vars:
        air: 1
        fire: 2
        water: 3
        earth: 4
        love: 5
        aziz: 'Light!'

    dest_fail:
      consul_key: templates/elements/aziz
      dest: rendered/nope/dest_fail.keep
      vars:
        aziz: 'Light!'

test:
  templates:
    secrets:
      path: templates/secrets.yml.erb
      dest: rendered/secrets.yml

production:
  templates:
    should_be_excluded:
      path: templates/fake.yml.erb
      dest: rendered/fake.yml
