env: test

shared:
  consul:
    address: http://0.0.0.0:8500

  vault:
    address: http://0.0.0.0:8200
    token: 94e1a9ed-5d72-5677-27ab-ebc485cca368

  templates:
    database:
      path: templates/database.yml.erb
      dest: rendered/database.yml
      ttl: 10 # seconds

test:
  templates:
    secrets:
      path: templates/secrets.yml.erb
      dest: rendered/secrets.yml

production:
  templates:
    should_be_excluded:
      path: templates/fake.yml.erb
      dest: rendered/fake.yml
