sudo: false
language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3

services:
  - docker

before_install:
  - gem install bundler -v 1.16.1
  - docker run -d --name=dev-consul -p 8500:8500 consul
  - docker run -d --name=dev-vault -p 8200:8200 --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=94e1a9ed-5d72-5677-27ab-ebc485cca368' vault
