version: '3'
services:
  consul:
    image: consul:1.2.0
    ports:
      - "8500:8500"
  vault:
    image: vault:0.10.3
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=94e1a9ed-5d72-5677-27ab-ebc485cca368
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
