version: 2
common_job_config: &common_job_config
    docker:
      - image: circleci/ruby:latest
      - image: consul:1.3.0
      - image: vault:0.11.3
        environment:
          - VAULT_DEV_ROOT_TOKEN_ID=94e1a9ed-5d72-5677-27ab-ebc485cca368
          # - SKIP_SETCAP=skip
        # cap_add:
        #   - IPC_LOCK

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: restore gem cache
          keys:
            - v1-bundle-{{ .Branch }}-{{ checksum "consult.gemspec" }}
            - v1-bundle-{{ .Branch }}-
            - v1-bundle-

      - run:
          name: install dependencies
          command: |
            bundle check --path ./vendor/bundle || bundle install --jobs=3 --retry=3 --path vendor/bundle
            bundle clean

      - save_cache:
          name: save gem cache
          paths:
            - ./vendor/bundle
          key: v1-bundle-{{ .Branch }}-{{ checksum "consult.gemspec" }}

      - run:
          name: setup fixture data
          command: |
            ./spec/support/populate_consul.sh

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results

            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
jobs:
  ruby_27:
    <<: *common_job_config
    docker:
      - image: circleci/ruby:2.7.0
      - image: consul:1.3.0
      - image: vault:0.11.3
        environment:
          - VAULT_DEV_ROOT_TOKEN_ID=94e1a9ed-5d72-5677-27ab-ebc485cca368
  ruby_26:
    <<: *common_job_config
    docker:
      - image: circleci/ruby:2.6.2
      - image: consul:1.3.0
      - image: vault:0.11.3
        environment:
          - VAULT_DEV_ROOT_TOKEN_ID=94e1a9ed-5d72-5677-27ab-ebc485cca368
  ruby_25:
    <<: *common_job_config
    docker:
      - image: circleci/ruby:2.5.3
      - image: consul:1.3.0
      - image: vault:0.11.3
        environment:
          - VAULT_DEV_ROOT_TOKEN_ID=94e1a9ed-5d72-5677-27ab-ebc485cca368
workflows:
  version: 2
  supported_ruby_versions:
    jobs:
      - ruby_27
      - ruby_26
      - ruby_25
